### ISSUE TITLE
Won't actually turn on the PS4

### ISSUE THREAD

**Issue by Rhoeffner** [luisiam/homebridge-cmdswitch#1]
I have setup the plugin to try and turn on my PS4. It does not recognize the correct state that the PS4 is in, and when I try to turn the PS4 on/off through siri it says it completes the process but nothing happens

**Comment by luisiam** [comment]
Have you install and setup the `ps4-waker` accordingly?

https://github.com/dhleong/ps4-waker

**Comment by Rhoeffner** [comment]
Sorry. Didn't realize you had to do that. Got it all setup and working. Thanks
