### ISSUE TITLE
What is this homebridge?

### ISSUE THREAD

**Issue by toshibochan** [luisiam/homebridge-cmdswitch#2]
What is this homebridge is for?

**Comment by luisiam** [comment]
To execute terminal command. For example, use `wol` to wake up a PC when I flip the switch to on and use `net rpc shutdown` to turn off the PC when I flip the switch to off. There are a lot of possibilities. I myself use it to turn on/off my PC and PS4.

**Comment by toshibochan** [comment]
I see! I was looking homebridge for use GPIO for relay to turn ON and OFF lights and switches. And I looking for my  sprinkler to.

**Comment by luisiam** [comment]
As long as you can control it in the terminal using command, this plugin should work
